version: "3.8"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: freelance_fast
    volumes:
      - ./app:/freelance/app
      - ./scripts/start.sh:/start.sh 
      - ./alembic:/freelance/alembic
      - ./alembic.ini:/freelance/alembic.ini
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=freelance.settings 
      - PYTHONUNBUFFERED=1
    command: 
     - sh 
     - -c
     - |
        chmod +x /start.sh && /start.sh
        
    depends_on: 
      - db
      - redis
  db:
    image: postgres:14.6-alpine
    container_name: db_freelance_fast
    hostname: db
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5433:5432"
  
  redis:
    image:
      redis
    environment:
      - REDIS_PASSWORD=redis
      - REDIS_USER=redis
    ports:
      - 6379:6379
    
volumes:
  db-data:
